POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "tfdsafsfas",
    "name": "Tatudadsa",
    "password": "1234",
    "email":"testikayttdsdaja@email.com",
    "phone": "0504543543545"
}
